import Navbar from "@/components/Navbar";
import { RecommendationProvider } from '@/context/RecommendationContext';
import { Providers } from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RecommendationProvider>
            <Navbar/>
            {children}
          </RecommendationProvider>
        </Providers>
      </body>
    </html>
  );
}
